# Site settings
title: Christopher Randall Wells
email: cwellsny@nycap.rr.com
description: "Chsritopher Randall Wells is an aspiring computer programmer. He is currently a senior in highschool, but will be attending the State University of New York at Oswego in the Fall of 2015 to pursue a degree in Computer Science."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christopher-randall-wells.divshot.io" # the base hostname & protocol for your site
twitter_username: ExcaliburZero_Z
github_username:  ExcaliburZero

# Set post urls to not use categories
permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown

# Ignore Divshot file
exclude:
  - divshot.json

# Gems
gems:
  - jekyll-sitemap # Generate sitemap for website
